apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
type: Opaque
data:
  # Replace the text below with your base64 encoded values.
  AZURE_STORAGE_CONNECTION_STRING: <base64-encoded-storage-account-connection-string>
