apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
type: Opaque
data:
  # Replace the text below with your base64 encoded values.
  AZURE_STORAGE_CONNECTION_STRING: <base64-encoded-storage-account-connection-string>
  AZURE_CONTAINER_NAME: <base64-encoded-container-name>
  AZURE_STORAGE_ACCOUNT: <base64-encoded-storage-account-name>
  